tnt: true
kit: true
enchant: true
crafting: true
pearl: true
sword: true

Panel:
  # OPCJE GUI
  GUI_NAME: "&8>> &7Admin Panel"

  # OPCJE PANELU
  TNT_NAME: "&cTNT"
  DIAMOND_HELMET_NAME: "&9Kity"
  ENCHANT_NAME: "&dEnchanty"
  DIAMOND_NAME: "&bCrafting diamentowych itemow"
  PEARL_NAME: "&3Perly"
  SWORD_NAME: "&cPVP"
  BARRIER_NAME: "&c&lWyjdz"
  PAPER_NAME: "&f&lManager"


Manage:
  GUI_NAME: "&8>> &7Manage"
  PAPER_NAME: "&f&lInformacje"
  RESET_NAME: "&eResetuj serwer"
  UNLAG_NAME: "&aOdlaguj serwer"
  OFF_NAME: "&cWylacz serwer"


# Wiadomosci
Messages:
  NO_PERMISSION: "&cNie posiadasz permisij!"


# Permisje
Permissions:
  PERMISSION: "xcode.adminpanel"